services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    container_name: postgres
    restart: unless-stopped
    
  ollama:
    image: ollama/ollama:0.1.43
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
      - ./dev-resources/ollama/entrypoint.sh:/entrypoint.sh
    labels:
      org.springframework.boot.service-connection: ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    # entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    entrypoint: ["sh", "-c", "ollama serve & sleep 10 && ollama pull llama3 && ollama pull nomic-embed-text && wait"]
    # if you have nvidia GPU, uncomment the following lines
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama: {}
